[build]
 #tell netlify where my files are
 publish = "frontend"

[[redirects]]
 from = "/"
 to = "/home.html"

[build]
  # This tells Netlify to look inside 'main_directory' for your HTML and CSS
  publish = "main_directory" 

[[redirects]]
  from = "/"
  to = "/home.html"
  status = 200